const { withGradleProperties } = require('@expo/config-plugins')

/**
 * Raises the Gradle JVM heap.
 *
 * Upstream ships Expo's default `-Xmx2048m`, which is not enough to dex this
 * project: `:app:mergeExtDexDebug` dies with a `DexArchiveMergerException`
 * carrying an empty message (the signature of an OOM in the dex merge worker)
 * after ~30 minutes of work. Measured on a 16 GB machine: 2 GB fails, 8 GB
 * succeeds.
 *
 * This has to be a config plugin rather than an edit to android/gradle.properties
 * — that directory is generated by prebuild and git-ignored, so a manual edit is
 * lost on the next `prebuild --clean`.
 *
 * `.cjs` because apps/wallet is an ESM package and Expo requires plugin files.
 */
const HEAP = '-Xmx8g'
const METASPACE = '-XX:MaxMetaspaceSize=1g'

module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (config) => {
    const properties = config.modResults.filter(
      (item) => !(item.type === 'property' && item.key === 'org.gradle.jvmargs')
    )
    properties.push({
      type: 'property',
      key: 'org.gradle.jvmargs',
      value: `${HEAP} ${METASPACE}`,
    })
    config.modResults = properties
    return config
  })
}
